// src/validationSchema.ts
import * as Yup from "yup";
import moment from "moment";

export const participants_schema = Yup.object().shape({
  civilite: Yup.string().required("Civilité est requise"),
  nom: Yup.string().required("Nom est requis"),
  prenom: Yup.string().required("Prénom est requis"),
  deuxiemeprenom: Yup.string(),
  organisme: Yup.string().required("Organisme est requis"),
  fonction: Yup.string().required("Fonction est requise"),
  email1: Yup.string().email("Email invalide").required("Email est requis"),
  email2: Yup.string().email("Email invalide"),
  telephone: Yup.string().required("Téléphone est requis"),
  adresse: Yup.string().required("Adresse est requise"),
  ville: Yup.string().required("Ville est requise"),
  pays: Yup.string().required("Pays est requis"),
  provenance: Yup.string().required("Provenance est requise"),
  forumDesJeunes: Yup.boolean(),
  forumDesFemmes: Yup.boolean(),
  forumScientifiques: Yup.boolean(),
  autreDocument: Yup.boolean(),
  lettreInvitation: Yup.boolean(),
  priseChargeBillet: Yup.boolean(),
  priseChargeComplete: Yup.boolean(),
  priseChargeHebergement: Yup.boolean(),
  reservationHotel: Yup.boolean(),
  priseChargetransUrbain: Yup.boolean(),
  autrePrecision: Yup.string(),
  autrePrecisionCharge: Yup.string(),
  dateDepart: Yup.date(),
  dateRetour: Yup.date(),
  villeDepart: Yup.string(),
  villeRetour: Yup.string(),
  passport: Yup.string(),
  biographie: Yup.string(),
  photo: Yup.string(),
  isSpeakers: Yup.boolean(),
  isParticipants: Yup.boolean(),
  isEtudiants: Yup.boolean(),
});

export const initialValues = {
  civilite: "",
  prenom: "",
  deuxiemeprenom: "",
  nom: "",
  email1: "",
  email2: "",
  telephone: "",
  organisme: "",
  fonction: "",
  adresse: "",
  ville: "",
  pays: "",
  provenance: "",
  dateDepart: moment().format("YYYY-MM-DD"),
  dateRetour: moment().format("YYYY-MM-DD"),
  villeDepart: "",
  villeRetour: "",
  passport: "null",
  photo: "",
  biographie: "",
  forumDesJeunes: false,
  forumDesFemmes: false,
  forumScientifiques: false,
  autreDocument: false,
  lettreInvitation: false,
  priseChargeBillet: false,
  priseChargeComplete: false,
  priseChargeHebergement: false,
  // reservationHotel: false,
  priseChargetransUrbain: false,
  autrePrecision: "",
  autrePrecisionCharge: "",
};

export const validationSchema = Yup.object().shape({
  civilite: Yup.string().required("Civilite est requis"),
  prenom: Yup.string().required("Prénom est requis"),
  deuxiemeprenom: Yup.string(),
  nom: Yup.string().required("Nom est requis"),
  email1: Yup.string()
    .email("Adresse email invalide")
    .required("Email est requis"),
  email2: Yup.string().email("Deuxième email invalide"),
  telephone: Yup.string().required("Téléphone est requis"),
  organisme: Yup.string().required("Organisme est requis"),
  fonction: Yup.string().required("Fonction est requise"),
  adresse: Yup.string().required("Adresse est requise"),
  ville: Yup.string().required("Ville est requise"),
  pays: Yup.string().required("Pays est requis"),
  provenance: Yup.string().required("Provenance est requise"),
  dateDepart: Yup.date(),
  dateRetour: Yup.date(),
  villeDepart: Yup.string(),
  villeRetour: Yup.string(),
  passport: Yup.string(),
  photo: Yup.string(),
  biographie: Yup.string(),
  forumDesJeunes: Yup.boolean(),
  forumDesFemmes: Yup.boolean(),
  forumScientifiques: Yup.boolean(),
  autreDocument: Yup.boolean(),
  lettreInvitation: Yup.boolean(),
  priseChargeBillet: Yup.boolean(),
  priseChargeComplete: Yup.boolean(),
  priseChargeHebergement: Yup.boolean(),
  reservationHotel: Yup.boolean(),
  priseChargetransUrbain: Yup.boolean(),
  autrePrecision: Yup.string(),
  autrePrecisionCharge: Yup.string(),
});
